# Generated by Django 2.2 on 2019-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleamarket', '0002_abstractad_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractad',
            name='header',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
