# Generated by Django 2.2 on 2019-04-28 01:08

from django.db import migrations, models
import fleamarket.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('fleamarket', '0003_abstractad_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractad',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=fleamarket.helpers.ImagePath('ads_images'), validators=[fleamarket.helpers.FileValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
